# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e9142b6b3ab47564c24c09a321d4b17eb1c1269049ba0c943f46ce2c7fce752d87a9d2d5000697fdbb20a78bbf3b683a5126e21c1f43b519d136d21920c8ca0

test:
  secret_key_base: 46c455cc76928dc71ae7f3ded48a7feb65c46b8cedb4935996eb9faef6a1570981e35aed7c728d6498230ec165e9330546181696850a24f3221e6c6b605245b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
